language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: matt2000
  password:
    secure: ZzKvLkmVDiCSvvjsCcYAfPtycMjQh6V0wJLkV+C0vWMzL5j0XPh/31xMASuW5+FwH0UWXH0gtXX2WdLJdgISZpsxGbi6sPf6eir202PqFh+hSd9Sr1Vh8XifkEeScQgLLCu2f0n9yHC6PJ6iUuFmStRsoX3AZ+VA5+BnR9dDv7N1UBt7K0P57fDe+UjDBq2F6miSTyYky8WrSuqiohePpupFWUCwS0Y/2ge2AZQffwuqcdTcs/IAYNC94o0vPDW8qgDRexhuyVf/zmoS3TlBT38qpwz92/9ayFJvYhN2hk2T3mVfg0dQ83ZgUXKzRv9ANMlUav/xmkMesGTLiTWsTRP/KVxyBRtCBvfGReQepUVWKqXm/HbRX6gxaHlriNdQaNZLoNJNJZf7M13P3+bfeU8vJ+6S/CEciPc0yKNpYKFh+Yhp2enYvjEFCTJh2tO24S2ZjEe4s3stKF3or7jwW74Yer0G9SOrVbQF0TF8mmuFb8GBh2npKC8S89yJ4iOf+VOoUDugfk020Hd7hbBpmPiVSGLFTFdH4uggXNsXjPaaxObpVY1IvDapxOQQAhy9zYrsIehxT1gsU6vgHnHFrUXSgLKeEDcJESHKuuhbwfniFS3Y0HHdVoTLakZzv0SB9bUxs3bSIj+JCoSObrRLIzY4KZiXTOlPGTd4fE8Oe8U=
  on:
    tags: true
    repo: matt2000/json_stream_reader
    python: 3.6
